FROM node:12.9.0-alpine

ENV APP_HOME /app
ENV PATH ${APP_HOME}/node_modules/.bin:$PATH
ENV TZ Asia/Tokyo
ENV HOST 0.0.0.0
ENV PORT 8080

WORKDIR ${APP_HOME}

COPY package.json .
ADD . ${APP_HOME}

RUN apk update && \
    apk upgrade && \
    npm install -g n && \
    yarn install &&\
    rm -rf /var/cache/apk/*

RUN yarn run build

EXPOSE ${PORT}

CMD ["yarn", "start"]